# This contains params to be used by the stages to train or predict
train_test_split:
  TEST_SIZE: 0.15
  RANDOM_STATE: 10

over_sample:
  RANDOM_STATE_OVER: 10

model_params:
  n_estimators: 150
  max_depth: 5
  min_samples_split: 4
  max_features: 50
